# Generated by Django 6.0.7 on 2026-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL slug')),
                ('category', models.CharField(choices=[('gardenNotes', 'Garden Notes'), ('seasonalTips', 'Seasonal Tips'), ('guestStories', 'Guest Stories')], default='gardenNotes', max_length=20, verbose_name='Category')),
                ('image', models.ImageField(blank=True, upload_to='journal/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('content', models.TextField(verbose_name='Content (HTML)')),
                ('description', models.TextField(blank=True, verbose_name='Short description (teaser)')),
                ('date', models.DateField(verbose_name='Publication date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Journal article',
                'verbose_name_plural': 'Journal articles',
                'ordering': ['-date'],
            },
        ),
    ]
