# Generated by Django 6.0.7 on 2026-07-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название домика')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(verbose_name='Описание и удобства')),
                ('max_guests', models.PositiveIntegerField(verbose_name='Макс. количество гостей')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
            ],
            options={
                'verbose_name': 'Гостевой дом',
                'verbose_name_plural': 'Гостевые дома',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/', verbose_name='Фотография')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guests.house', verbose_name='Домик')),
            ],
            options={
                'verbose_name': 'Фотография домика',
                'verbose_name_plural': 'Фотографии домиков',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Имя гостя')),
                ('guest_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('PENDING', 'Новая заявка'), ('CONFIRMED', 'Подтверждено'), ('CANCELED', 'Отклонено')], default='PENDING', max_length=20, verbose_name='Статус заявки')),
                ('comment', models.TextField(blank=True, verbose_name='Пожелания гостя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.house', verbose_name='Выбранный домик')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'indexes': [models.Index(fields=['status', 'check_in'], name='guests_book_status_eab6ae_idx')],
            },
        ),
    ]
