# Generated by Django 6.0.7 on 2026-07-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('category', models.CharField(choices=[('garden', 'Garden'), ('house', 'House'), ('workshop', 'Workshop'), ('greenhouse', 'Greenhouse')], default='garden', max_length=50, verbose_name='Категория')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Фотографии галереи',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
